README.md
doc: Fix typos, and edit copy.
The deleted bounty was (I believe) closed by #81.
=> doc: Fix typos, and edit copy.

.github/actions/create-env-file/action.yml, .github/workflows/deploy.yml
=> Fix deploy action

src/scrappers/github.yml
N/A
Add support for GitHub issues list.
=> feat: add support for Github issues

src/scrappers/youtube.yml
First of all, thanks for open-sourcing this cool project.
While using it, I realized that scraping video information from Youtube playlists is not yet supported. So I added the support with the changes in this PR.
Also, getting the video duration was broken which I also fixed.
=> feat: add support for scraping video information from Youtube playlist

src/scrappers/linkedin-groups.yml
N/A
Add scrapper for LinkedIn Groups.
=> feat: add scrapper for LinkedIn Groups

src/scrappers/gads-keyword-planner.yml
Added a new scrapper for the Google Ads Keyword planner tables.
=> feat:add new scrapper, gads planner

src/scrappers/ikea.yml
=> feat: add ikea scrapper

src/scrappers/annuairevert-magasins.yml, src/scrappers/annuairevert-produits.yml, src/scrappers/byggdinframtid.yml, src/scrappers/voeazul.yml
Add scrapers to the following sites:
- voeazul
- annuairevert
- byggdinframtid
=> Add requested sites

package.json, src/scrappers/babymarket-list-products.yml, src/scrappers/babyone.yml, src/scrappers/babypark-de-list-products.yml, src/scrappers/babypark-nl-list-products.yml, src/scrappers/bebe9.yml, src/scrappers/bol.yml, src/scrappers/cdiscount.yml, src/scrappers/dreambaby.yml, src/scrappers/johnlewis.yml, src/scrappers/jollyroom.yml, src/scrappers/pinkorblue-list-products-it.yml, src/scrappers/pinkorblue-list-products-nl.yml, src/scrappers/pinkorblue-list-products.yml, src/scrappers/rosaoazul-es-list-products.yml, src/scrappers/roseoubleu-fr-list-products.yml
This PR intends to 
- Add missing fields in some websites
- Fix the scraper in some websites
=> Fix some websites scrapers

.releaserc
=> feat(release-rules): fix release rules

src/background.ts
N/A
This PR intends to add a feedback form when a user decides to uninstall the extension. This will help us understand why the user decided to do it and use that feedback to improve the extension.
=> feat(core): add uninstall form

src/scrappers/racius.yml
=> feat(scraper): add `racius.com` scraper

package-lock.json, src/scrappers/gumroad.yml, src/scrappers/recheio.yml
N/A
Add scrapers to the following sites:
- recheio.pt
- gumroad.com
=> Add 2 new scrapers

src/scrappers/babyone.yml, src/scrappers/prenatal-com.yml, src/scrappers/prenatal-nl.yml
=> Add 2 websites scrapers

package-lock.json, package.json
I am bumping the package's version manually.
=> fix(core): bump package manually

src/scrappers/suchen-mobile-park.yml, src/scrappers/suchen-mobile.yml, src/utils/scrappers/custom.ts
N/A
This PR intends to:
- Fix mobile.de ads scraper
- Add mobile.de park scraper
=> feat(core): add mobile.de park scraper

package-lock.json, src/scrappers/g2-reviews.yml
https://github.com/rows/issues/issues/1707
Fix bug related to G2 pagination.
The extension wasn't working when requesting reviews after the first page (with the following URL `https://www.g2.com/products/productboard/reviews?page=2`).
=> fix(g2-scraper): fix bug with pagination

src/scrappers/capterra-de.yml
=> feat: add capterra.de scraper

src/scrappers/ocean.io.yml
=> Add `ocean.io` scraper

src/scrappers/capterra.yml
=> feat: add capterra.com scraper

src/scrappers/facebook.yml
Add Facebook post comments scraper.
=> feat: add facebook post comments scraper

package-lock.json, package.json
https://github.com/rows/X/security/dependabot/13
=> chore: bump vite v5.4.12
